CREATE TABLE tb_bidang_urusan (
    id VARCHAR(255),
    kode_bidang_urusan VARCHAR(255) NOT NULL,
    nama_bidang_urusan VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;