CREATE TABLE tb_pegawai (
    id VARCHAR(36) NOT NULL ,
    nama VARCHAR(255) NOT NULL,
    nip VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;