CREATE TABLE tb_pelaksana_pokin (
    Id VARCHAR(255) NOT NULL ,
    pohon_kinerja_id VARCHAR(255) NOT NULL,
    pegawai_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;
