CREATE TABLE tb_tahun_periode (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_periode INT,
    tahun VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;