CREATE TABLE tb_rincian_belanja (
    id INT AUTO_INCREMENT PRIMARY KEY,
    renaksi_id VARCHAR(255) NOT NULL,
    anggaran BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;