CREATE TABLE tb_master_tagging (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_tagging VARCHAR(255) NOT NULL,
    keterangan_tagging TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;