name: Commit stage

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check formatting
        run: make check-format

      - name: Run tests
        run: make test

      - name: Check compilation
        run: make build

      - name: Build Docker image
        run: make build-image
